[project]
name = "call-me-1337-42"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "momahdam", email = "medamin.mahdam@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "numpy>=2.4.6",
    "pydantic>=2.13.5",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
call-me-1337-42 = "call_me_1337_42:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
exclude = ["llm_sdk"]

[[tool.mypy.overrides]]
module = "llm_sdk.*"
ignore_errors = true
follow_imports = "skip"